#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Strainer.Droid.Resource", IsApplication=true)]

namespace Strainer.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.ApplicationName = global::Strainer.Droid.Resource.String.ApplicationName;
			global::Cirrious.MvvmCross.Droid.FullFragging.Resource.String.Hello = global::Strainer.Droid.Resource.String.Hello;
			global::Amp.Resource.Attribute.AccessoryTemplate = global::Strainer.Droid.Resource.Attribute.AccessoryTemplate;
			global::Amp.Resource.Attribute.ContentTemplate = global::Strainer.Droid.Resource.Attribute.ContentTemplate;
			global::Amp.Resource.Attribute.FallbackImage = global::Strainer.Droid.Resource.Attribute.FallbackImage;
			global::Amp.Resource.Attribute.LoadMoreItemTemplate = global::Strainer.Droid.Resource.Attribute.LoadMoreItemTemplate;
			global::Amp.Resource.Attribute.MvxBind = global::Strainer.Droid.Resource.Attribute.MvxBind;
			global::Amp.Resource.Attribute.MvxDropDownItemTemplate = global::Strainer.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::Amp.Resource.Attribute.MvxItemTemplate = global::Strainer.Droid.Resource.Attribute.MvxItemTemplate;
			global::Amp.Resource.Attribute.MvxLang = global::Strainer.Droid.Resource.Attribute.MvxLang;
			global::Amp.Resource.Attribute.MvxSource = global::Strainer.Droid.Resource.Attribute.MvxSource;
			global::Amp.Resource.Attribute.MvxTemplate = global::Strainer.Droid.Resource.Attribute.MvxTemplate;
			global::Amp.Resource.Attribute.Template = global::Strainer.Droid.Resource.Attribute.Template;
			global::Amp.Resource.Attribute.View = global::Strainer.Droid.Resource.Attribute.View;
			global::Amp.Resource.Attribute.footer = global::Strainer.Droid.Resource.Attribute.footer;
			global::Amp.Resource.Attribute.header = global::Strainer.Droid.Resource.Attribute.header;
			global::Amp.Resource.Id.MvxBindingTagUnique = global::Strainer.Droid.Resource.Id.MvxBindingTagUnique;
			global::Amp.Resource.Id.accessoryView = global::Strainer.Droid.Resource.Id.accessoryView;
			global::Amp.Resource.Id.container = global::Strainer.Droid.Resource.Id.container;
			global::Amp.Resource.Id.contentView = global::Strainer.Droid.Resource.Id.contentView;
			global::Amp.Resource.Id.delete = global::Strainer.Droid.Resource.Id.delete;
			global::Amp.Resource.Id.dialog_buttonsLinearLayout = global::Strainer.Droid.Resource.Id.dialog_buttonsLinearLayout;
			global::Amp.Resource.Id.dialog_message = global::Strainer.Droid.Resource.Id.dialog_message;
			global::Amp.Resource.Id.linearLayout1 = global::Strainer.Droid.Resource.Id.linearLayout1;
			global::Amp.Resource.Id.listView = global::Strainer.Droid.Resource.Id.listView;
			global::Amp.Resource.Id.monthPicker = global::Strainer.Droid.Resource.Id.monthPicker;
			global::Amp.Resource.Id.numberPicker = global::Strainer.Droid.Resource.Id.numberPicker;
			global::Amp.Resource.Id.okButton = global::Strainer.Droid.Resource.Id.okButton;
			global::Amp.Resource.Id.scrollView = global::Strainer.Droid.Resource.Id.scrollView;
			global::Amp.Resource.Id.textView = global::Strainer.Droid.Resource.Id.textView;
			global::Amp.Resource.Id.textView1 = global::Strainer.Droid.Resource.Id.textView1;
			global::Amp.Resource.Id.yearPicker = global::Strainer.Droid.Resource.Id.yearPicker;
			global::Amp.Resource.Layout.Cell_SwipableListItemView = global::Strainer.Droid.Resource.Layout.Cell_SwipableListItemView;
			global::Amp.Resource.Layout.Cell_SwipableListItemView_DefaultAccessoryView = global::Strainer.Droid.Resource.Layout.Cell_SwipableListItemView_DefaultAccessoryView;
			global::Amp.Resource.Layout.Template_DefaultListItem = global::Strainer.Droid.Resource.Layout.Template_DefaultListItem;
			global::Amp.Resource.Layout.Template_DefaultSpinnerItem = global::Strainer.Droid.Resource.Layout.Template_DefaultSpinnerItem;
			global::Amp.Resource.Layout.View_DefaultDialog = global::Strainer.Droid.Resource.Layout.View_DefaultDialog;
			global::Amp.Resource.Layout.View_DefaultListPicker = global::Strainer.Droid.Resource.Layout.View_DefaultListPicker;
			global::Amp.Resource.Layout.View_MonthYearDatePicker = global::Strainer.Droid.Resource.Layout.View_MonthYearDatePicker;
			global::Amp.Resource.Layout.View_NumberPicker = global::Strainer.Droid.Resource.Layout.View_NumberPicker;
			global::Amp.Resource.String.ApplicationName = global::Strainer.Droid.Resource.String.ApplicationName;
			global::Amp.Resource.String.Hello = global::Strainer.Droid.Resource.String.Hello;
			global::Amp.Resource.String.library_name = global::Strainer.Droid.Resource.String.library_name;
			global::Amp.Resource.Style.dialog_buttonDefault = global::Strainer.Droid.Resource.Style.dialog_buttonDefault;
			global::Amp.Resource.Style.dialog_themeDefault = global::Strainer.Droid.Resource.Style.dialog_themeDefault;
			global::Amp.Resource.Styleable.Behavior = global::Strainer.Droid.Resource.Styleable.Behavior;
			global::Amp.Resource.Styleable.Behavior_View = global::Strainer.Droid.Resource.Styleable.Behavior_View;
			global::Amp.Resource.Styleable.BindableImageViewBehavior = global::Strainer.Droid.Resource.Styleable.BindableImageViewBehavior;
			global::Amp.Resource.Styleable.BindableImageViewBehavior_FallbackImage = global::Strainer.Droid.Resource.Styleable.BindableImageViewBehavior_FallbackImage;
			global::Amp.Resource.Styleable.ContentPresenter = global::Strainer.Droid.Resource.Styleable.ContentPresenter;
			global::Amp.Resource.Styleable.ContentPresenter_Template = global::Strainer.Droid.Resource.Styleable.ContentPresenter_Template;
			global::Amp.Resource.Styleable.ListView = global::Strainer.Droid.Resource.Styleable.ListView;
			global::Amp.Resource.Styleable.ListView_footer = global::Strainer.Droid.Resource.Styleable.ListView_footer;
			global::Amp.Resource.Styleable.ListView_header = global::Strainer.Droid.Resource.Styleable.ListView_header;
			global::Amp.Resource.Styleable.ListViewInfiniteScrollBehavior = global::Strainer.Droid.Resource.Styleable.ListViewInfiniteScrollBehavior;
			global::Amp.Resource.Styleable.ListViewInfiniteScrollBehavior_LoadMoreItemTemplate = global::Strainer.Droid.Resource.Styleable.ListViewInfiniteScrollBehavior_LoadMoreItemTemplate;
			global::Amp.Resource.Styleable.MvxBinding = global::Strainer.Droid.Resource.Styleable.MvxBinding;
			global::Amp.Resource.Styleable.MvxBinding_MvxBind = global::Strainer.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::Amp.Resource.Styleable.MvxBinding_MvxLang = global::Strainer.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::Amp.Resource.Styleable.MvxControl = global::Strainer.Droid.Resource.Styleable.MvxControl;
			global::Amp.Resource.Styleable.MvxControl_MvxTemplate = global::Strainer.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::Amp.Resource.Styleable.MvxImageView = global::Strainer.Droid.Resource.Styleable.MvxImageView;
			global::Amp.Resource.Styleable.MvxImageView_MvxSource = global::Strainer.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::Amp.Resource.Styleable.MvxListView = global::Strainer.Droid.Resource.Styleable.MvxListView;
			global::Amp.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Strainer.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::Amp.Resource.Styleable.MvxListView_MvxItemTemplate = global::Strainer.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Amp.Resource.Styleable.SwipeableListView = global::Strainer.Droid.Resource.Styleable.SwipeableListView;
			global::Amp.Resource.Styleable.SwipeableListView_AccessoryTemplate = global::Strainer.Droid.Resource.Styleable.SwipeableListView_AccessoryTemplate;
			global::Amp.Resource.Styleable.SwipeableListView_ContentTemplate = global::Strainer.Droid.Resource.Styleable.SwipeableListView_ContentTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int AccessoryTemplate = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int ContentTemplate = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int FallbackImage = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int LoadMoreItemTemplate = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int MvxBind = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int MvxDropDownItemTemplate = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int MvxItemTemplate = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int MvxLang = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int MvxSource = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int MvxTemplate = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int Template = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int View = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int footer = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int header = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int accessoryView = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int container = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int contentView = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int delete = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int dialog_buttonsLinearLayout = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int dialog_message = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int linearLayout1 = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int listView = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int monthPicker = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int myButton = 2130968582;
			
			// aapt resource value: 0x7f040010
			public const int numberPicker = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int okButton = 2130968591;
			
			// aapt resource value: 0x7f040002
			public const int scrollView = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int textView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int textView1 = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int yearPicker = 2130968590;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Cell_SwipableListItemView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Cell_SwipableListItemView_DefaultAccessoryView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Template_DefaultListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Template_DefaultSpinnerItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int View_DefaultDialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int View_DefaultListPicker = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int View_MonthYearDatePicker = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int View_NumberPicker = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int dialog_buttonDefault = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dialog_themeDefault = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Behavior = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int Behavior_View = 0;
			
			public static int[] BindableImageViewBehavior = new int[]
			{
					2130771975};
			
			// aapt resource value: 0
			public const int BindableImageViewBehavior_FallbackImage = 0;
			
			public static int[] ContentPresenter = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int ContentPresenter_Template = 0;
			
			public static int[] ListView = new int[]
			{
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public const int ListView_footer = 1;
			
			// aapt resource value: 0
			public const int ListView_header = 0;
			
			public static int[] ListViewInfiniteScrollBehavior = new int[]
			{
					2130771969};
			
			// aapt resource value: 0
			public const int ListViewInfiniteScrollBehavior_LoadMoreItemTemplate = 0;
			
			public static int[] MvxBinding = new int[]
			{
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771978};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771981};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SwipeableListView = new int[]
			{
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public const int SwipeableListView_AccessoryTemplate = 0;
			
			// aapt resource value: 1
			public const int SwipeableListView_ContentTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
